version: '3'
services:
  badstore:
    image: jvhoof/badstore-docker
    container_name: badstore
    networks:
      - mi_red
    ports:
      - "80:80"

  owaszap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: owaszap
    user: zap
    networks:
      - mi_red
    ports:
      - "8080:8080"
      - "8090:8090"
    command: zap-webswing.sh

networks:
  mi_red:
    external: true