version: '3'
services:
  beautiful_chatele:
    image: jvhoof/badstore-docker
    container_name: beautiful_chatele
    networks:
      - mi_red
    ports:
      - "80:80"

  friendly_bhabha:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: friendly_bhabha
    user: zap
    networks:
      - mi_red
    ports:
      - "8080:8080"
      - "8090:8090"
    command: zap-webswing.sh

networks:
  mi_red:
    external: true